# TH3 Buildspec for AWS CodeBuild segment of CodePipeline
#
# @author Nick Stires <nick@nmetech.com>
# @link https://console.aws.amazon.com/codesuite/codepipeline/pipelines/th3/view?region=us-east-1
#
# Build environment is AmazonLinux 2 container
# Redis hosted via AWS ElasticCache
#
# ------------------------------------------------------------------------------

version: 0.2

run-as: root

env:
  shell: bash
  variables:
    REDIS_ADDR: "th3-test.wau2ig.0001.use1.cache.amazonaws.com"
  git-credential-helper: no

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install -r requirements.txt # App reqs.
      - pip3 install pylint pyinstaller
      - mkdir artifacts_out/
      - export VERSION=`grep "^__version__" src/th3_server.py | awk -F\" '{print $2}'`
  pre_build:
    commands:
      - pylint --rcfile=.pylintrc --fail-under=8 src/th3_server.py > artifacts_out/th3_server_${VERSION}.out
  build:
    commands:
      - pyinstaller --onefile --distpath artifacts_out/ src/th3_server.py
artifacts:
  files:
    - 'artifacts_out/*'
